# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'
      
services:
  autodocapi:
    image: autodocapi
    container_name: autodoc.api
    build:
      context: .
      dockerfile: AutoDocApi/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      autodoc.database:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      
  autodoc.database:
    image: postgres:latest
    container_name: autodoc.database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: autodoc
    volumes:
      - ./.containers/autodoc-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  